### PR TITLE
Search: enable for ko; fix ja; hide for zh-*

### LINKED ISSUE #949: Warning due to recent lunr changes
Can we do something about this?

image

Presumably due to #943

### PR DESCRIPTION
**Pull request by microbit-robert**
- Omit lunr warnings emitted when changing languages.
- Hide search where it is not supported for a language (currently zn, ko). 

Closes #949.

### CODE REVIEW

**Comment by microbit-robert** [comment]
In draft as I will also look at the tokenizer issue for search input with Japanese as the selected language.

**Comment by microbit-matt-hillsdon** [comment]
I think I'm happy with this.

**Comment by microbit-matt-hillsdon** [comment]
With @microbit-robert for further testing after today's changes.

**Comment by microbit-robert** [comment]
@microbit-matt-hillsdon All looks good to me!

**Pull request merged**
