### PR TITLE
Remove unintended "it.only"s.

### PR DESCRIPTION
**Pull request by microbit-matt-hillsdon**
Oops. Would be nice to lint this.

### CODE REVIEW

**Comment by microbit-matt-hillsdon** [comment]
Failed in one of the enabled e2e tests.

**Comment by microbit-matt-hillsdon** [comment]
No logging.
image

**Comment by microbit-matt-hillsdon** [comment]
2nd failure seems to be flakiness in unrelated tests. Hoping for a pass on re-run. I'll go back over recent failures later today.

**Review by microbit-robert — APPROVED** [review]
LGTM.

**Pull request merged**
