### PR TITLE
Update stubs for MicroPython updates.

### PR DESCRIPTION
**Pull request by microbit-matt-hillsdon**
Only the English stubs have a meaningful upgrade here. We'll need a translation roundtrip for the others.

Stubs PR: https://github.com/microbit-foundation/micropython-microbit-stubs/pull/56

These stubs correspond to this beta MicroPython release: https://github.com/microbit-foundation/micropython-microbit-v2/releases/tag/v2.1.0-beta.1

Further more minor updates are expected for the 2.1.0 release.

### CODE REVIEW

**Comment by microbit-matt-hillsdon** [comment]
@microbit-robert please review but hold off from merging until we've settled plans re translation.

**Comment by microbit-robert** [comment]
There's a strange extra space here, but I can't see why in the stubs PR:

image

**Review by microbit-robert — APPROVED** [review]
LGTM.

**Comment by microbit-matt-hillsdon** [comment]
> There's a strange extra space here, but I can't see why in the stubs PR:
> 
> image

Raised https://github.com/microbit-foundation/python-editor-next/issues/938

**Pull request merged**
