### PR TITLE
Update Codemirror

### LINKED ISSUE #559: Upgrade CodeMirror to latest version
Upgrade CodeMirror to latest version and test/check for any negative side effects/errors. Note to check indentation specifically.

### LINKED ISSUE #606: Delay on hover makes you miss error context
Not sure if this is by design, but adding this for discussion as it came up in a user interview

When you hover over an error, it seems to take a long time for the error message to appear.

Screen Recording 2022-02-18 at 09 29 57 am

If you don't dwell for long enough, you can easily miss the fact that there is some extra context available to help you fix the issue.

### PR DESCRIPTION
**Pull request by microbit-robert**
Upgrade CodeMirror to latest version.

Closes #559 
Closes #606 - see https://discuss.codemirror.net/t/hover-delay-for-lint-errors/4025

### CODE REVIEW

**Comment by microbit-robert** [comment]
@microbit-matt-hillsdon Please check that nothing is broken in CodeMirror.

**Comment by microbit-matt-hillsdon** [comment]
There's a theming issue of some sort: 

image

**Comment by microbit-matt-hillsdon** [comment]
Changing font size breaks code structure highlighting.

**Comment by microbit-matt-hillsdon** [comment]
> Changing font size breaks code structure highlighting.

Wow, it also breaks the gutter. We should check we've not missed release notes about reconfiguring the editor and see if it repros in a simpler setup.

**Comment by microbit-matt-hillsdon** [comment]
CM bug is fixed. Looks good to me. No release yet.

@microbit-robert, I've pushed a branch with a locally built tgz to https://review-python-editor-next.microbit.org/cm-update-fixed/ so you can try it out.

**Comment by microbit-robert** [comment]
Latest release fixes previous bug of the view (gutter and structure highlighting) not being properly updated on changing font size. However, the update introduces a new bug previously observed in our locally patched version. 

If there is a space or dot after word, the cursor jumps down to the next line, which exists between the gutter line numbers.

image

**Comment by microbit-matt-hillsdon** [comment]
Somewhat unexpectedly, this branch doesn't have height overflow on iPad whereas that's a known issue on main.
I got "An error occurred loading the toolkit" on iPad too, which is interesting. Same is true of other recent review branches so not new here, just noting for reference.

**Comment by microbit-matt-hillsdon** [comment]
This seems to be working well. @microbit-robert is there any reason for it to still be draft? Any remaining concerns?

**Review by microbit-matt-hillsdon — APPROVED** [review]

**Pull request merged**
