### PR TITLE
Allow digits in filenames.

### LINKED ISSUE #524: "Create file" confusingly rejects filenames with digits/numbers/numerals
image

It doesn't mention that the digits are a problem. We should check the real restriction and either adjust it or the error text.

Reported by @microbit-katie

### PR DESCRIPTION
**Pull request by microbit-matt-hillsdon**
Closes #524.

### CODE REVIEW

**Review by microbit-robert — CHANGES_REQUESTED** [review]
While you can have python files/modules that start with a number run okay in isolation, Python doesn't let you import from files/modules that start with a number. We either need to disallow numbers again with the appropriate error message, or cater for Python's naming conventions by changing the regex (and probably adding another message to the user).

**Comment by microbit-matt-hillsdon** [comment]
Thanks, obvious now you point it out! 
Makes me less inclined to do this partial fix.
The original was based on https://www.python.org/dev/peps/pep-0008/#package-and-module-names (which I failed to find yesterday). Will revisit this later.

**Comment by microbit-matt-hillsdon** [comment]
Support ticket: https://support.microbit.org/a/tickets/54238 

This was just raised independently via support.

**Comment by microbit-matt-hillsdon** [comment]
Superseded by https://github.com/microbit-foundation/python-editor-next/pull/770

**Pull request closed without merging**
